name: qsar50s
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - rdkit
  - openjdk
  - pyyaml
  - jupyter
  - scipy
  - plotly
  - biopython
  - pip
  - pip:
    - padelpy
    - molfeat
    - git+https://github.com/EBjerrum-chem/qsprutils.git
    - git+https://github.com/charnley/chemschematicresolver.git